server:
  port: 8086

database:
  mysql:
    ip: 119.3.105.213
    port: 3306
    dbname: base
    username: root
    password: 1024@Augo

spring:
  redis:
    host: localhost
    port: 6379
    #    password: augo1024
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
  datasource:
    url: jdbc:mysql://${database.mysql.ip}:${database.mysql.port}/${database.mysql.dbname}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${database.mysql.username}
    password: ${database.mysql.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 3
      maximum-pool-size: 8
      connection-test-query: SELECT 1
      connection-timeout: 6000

## mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.merryyou.security.model
  global-config:
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断" ,2:"非空判断"
      field-strategy: not_empty
      db-type: mysql
  configuration:
    #使用驼峰法映射属性
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    org.springframework: info

merryyou:
  security:
    oauth2:
      storeType: jwt #或者jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: order123
      clients[1]:
              clientId: merryyou1
              clientSecret: order123
